experiment:
  name: dc/cgeff/cgqa/r1
dataset:
  data_dir: cgqa
  dataset: cgqa
  splitname: compositional-split-natural
model_params:
  model: graphfull
  dropout: true
  norm: true
  nlayers: 3
  fc_emb: 768,1024,1200
  gr_emb: d4096,d
  emb_dim: 600
  emb_init: null
  graph_init: w2v_corrected.t7
  eval_type: otherdist
  image_extractor: resnet18
  train_only: true
  static_inp: false
gcnii:
  hidden_dim: 1024
  gcn_type: gcn
  gcn_nlayers: 10
training:
  batch_size: 256
  eval_val_every: 2
  load:
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-06
  margin: 2
  max_epochs: 2000
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 256
  test_set: val
  topk: 1
  workers: 8
  update_features: false
  freeze_featues: false
