experiment:
  name: graphembed/cgqa
dataset:
  data_dir: cqga
  dataset: cgqa
  splitname: compositional-split-natural
model_params:
  model: graphfull
  entropy: true
  pseudo: false
  dropout: true
  norm: true
  nlayers: 1
  fc_emb: 768,1024,1200
  gr_emb: d600,d
  emb_dim: 300
  emb_init: word2vec
  graph_init: 
  eval_type: otherdist
  image_extractor: resnet18
  train_only: false
  static_inp: false
gcnii:
  hidden_dim: 1024
  gcn_type: gcn
  gcn_nlayers: 10
training:
  batch_size: 256
  eval_val_every: 20
  load:
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-06
  margin: 2
  max_epochs: 80
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  workers: 8
  update_features: true
  freeze_featues: false
