---
experiment:
  name: graphembed/mitstates/base
dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural
model_params:
  model: graphfull
  dropout: true
  norm: true
  nlayers: 2 
  gr_emb: d600,d
  emb_dim: 300
  emb_init: word2vec
  graph_init:
  image_extractor: resnet18
  train_only: false
  static_inp: false
training:
  batch_size: 128
  eval_val_every: 10
  load: 
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  margin: 0.5
  max_epochs: 200
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  workers: 8
  update_features: false
  freeze_features: false

