---
experiment:
  name: kgsp/mitstates
dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural
model_params:
  model: kgsp
  gumbel: true
  partial: true
  kbfile: utils/mit_conceptnet.npy
  dropout: true
  norm: true
  image_extractor: resnet18
  train_only: false
  static_inp: false
  emb_init: word2vec
  input_dim: 300
training:
  batch_size: 256
  eval_val_every: 10
  load: 
  lr: 5.0e-05
  wd: 5.0e-05
  lrg: 5.0e-6
  max_epochs: 200
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 32
  test_set: val
  topk: 1
  workers: 8
  update_features: true
  freeze_features: false

